### ISSUE TITLE
User-defined palette for image plots

### ISSUE THREAD

**Issue by dtimson** [jkriege2/JKQtPlotter#10]
As far as I can see, it's not possible to define & use an arbitrary palette for image plots.

Looking at the code, it seems that a few changes to JKQTPMathImage would support this, making use of the JKQTPMathImageUSER_PALETTE option. Would it be OK if I sent a pull-request to show you what I mean?

PS - thanks for writing a great library!

**Comment by jkriege2** [comment]
Hi!

that's one of the open things I still wanted to tackle ... so I would be happy to look over such a commit! ... You should also put your extension into JKQTPColorPaletteStyleAndToolsMixin (used for colored scatter-plots etc.) as at some point that will be used by JKQTPMathImage (currently that's still partly doubled code)!


In addition I was planning on reactivating a system that is in place for some time and allows to read palettes from files. That way it will be possible to register palettes (either user-defined, or from files) with IDs above JKQTPMathImagePREDEFINED_PALETTES_COUNT at a central place and they can simply be used by defining palette JKQTPMathImagePREDEFINED_PALETTES_COUNT+1, JKQTPMathImagePREDEFINED_PALETTES_COUNT+2, ... (enum is more or less simply an INT ;-)

So ... looking forward to you extensions!

PS - Great to hear you like the lib ... what are you using it for?

**Comment by jkriege2** [comment]
Hi again!

just a short word of warning ... I'm currently reworking the palettes backend system (types and all) ... so you might want to wait until that is pushed to the repository!

Best,
JAN

**Comment by jkriege2** [comment]
Hi!

please have a look at my last commit https://github.com/jkriege2/JKQtPlotter/commit/9f694a9f91a1a129a06cf8dfe9fc7f383e59a0cc ... maybe that already solves your task?

There is also a new example for user-defined palettes with a tutorial:
https://github.com/jkriege2/JKQtPlotter/tree/master/examples/imageplot_userpal

Best,
JAN

**Comment by dtimson** [comment]
Thanks Jan - that's just what I needed.

I'm using the library to plot the results of analyzing RF signals of various kinds: image plots (spectrograms), line plots etc.

Thanks again,
Dan
