### ISSUE TITLE
Lock the panning action to certain values

### ISSUE THREAD

**Issue by sim186** [jkriege2/JKQtPlotter#110]
Hi Jan,

sorry for asking so many question but I was wondering if there is a way to "lock" the panning action with mouse below the origin point of the axis (or whatever point is reasonable). I would like to block to user to scroll to regions of the plot where I do not have values (like negative values).

I saw that is possible to manipulate the values on the axis but I cannot find a way to prevent the panning.

Thanks

**Comment by jkriege2** [comment]
Have a look at JKQTPCoordinateAxis::setAbsoluteRange() that sets a limit for the axis range, so you cannot zoom/pan beyond that range ... e.g. set it to JKQTPCoordinateAxis::setAbsoluteRange(0, DBL_MAX) for [0...MAX].

Let me know if it works or whether there is still a bug (quite possible ;-)
best,
JAN

**Comment by sim186** [comment]
Hi,

yes looks like is working I was able to lock the panning up to the origin on the left side. The only problem is that when I try to pan towards the limit the plot get zommed in. This must be some mouse event connected to the drag action.

**Comment by jkriege2** [comment]
Hi!

OK, I will look into this ... but give me some timme ;-)

Best,
JAN

**Comment by jkriege2** [comment]
fixed via https://github.com/jkriege2/JKQtPlotter/commit/99ff39a3d62d778117c161ce50e36a61460973af

Thanks for reporting

**Comment by sim186** [comment]
With pleasuere. Never enough for let us use this amazing library!

**Comment by sim186** [comment]
Hi Jan,

just pulled master, probably I am wrong and I am not setting the right thing, but this is what I get while panning
![zoom_while_panning](https://github.com/jkriege2/JKQtPlotter/assets/18590835/ae101aca-85e4-4ffd-88d7-1ac03ebec140)

and setting the plot in this way:
```cpp
m_ui->m_plot->getXAxis()->setAbsoluteRange(0, DBL_MAX);
m_ui->m_plot->getYAxis()->setAbsoluteRange(0, DBL_MAX);
```

and the pan action is done is this way:
`m_ui->m_plot->registerMouseDragAction(Qt::LeftButton, Qt::NoModifier, static_cast<JKQTPMouseDragActions>(jkqtpmdaPanPlotOnMove));`

Am I doing something wrong?

**Comment by jkriege2** [comment]
OK, I think I found the bug (see https://github.com/jkriege2/JKQtPlotter/commit/ae157d928b7f14e6913d3b361ebd05a45644030d) ... it works for me now! Can you check too?

**Comment by sim186** [comment]
It worked like a charm for using the latest master. Great!
