### ISSUE TITLE
Create v4.0.1 tag?

### ISSUE THREAD

**Issue by arBalasquide** [jkriege2/JKQtPlotter#113]
v4.0.0 has a typo in the CMake, which was fixed in a later commit, that caused some includes to be missing on an install. Would be nice to bump the release so others don't go to v4.0.0 and waste time figuring out why their build isn't working.

Thanks!

**Comment by jkriege2** [comment]
Do you remember which fixes are neccesarry?
Otherwise I'm hoping to make a new 5.0.0 release soon!

**Comment by arBalasquide** [comment]
Yes, it was a typo https://github.com/jkriege2/JKQtPlotter/blob/d45083ee9bdd96de1a381ad0d63c4ba8ef547e5c/lib/jkqtplotter/CMakeLists.txt#L310

It should be `HEADERS_BASE`. Already fixed in a later commit, but causes build issues in the 4.0.0 release. If a new release is coming soon anyhow, then its no big deal.

**Comment by jkriege2** [comment]
https://github.com/jkriege2/JKQtPlotter/releases/tag/v4.0.1 should fix the bug!
