### ISSUE TITLE
Unnecessary printing of tilde symbol in math

### ISSUE THREAD

**Issue by igormironchik** [jkriege2/JKQtPlotter#117]
Not sure what is the issue, but I guess it's a very low effort to you to fix. Look, a following LaTeX math renders tildes, whereas all known to me other renders don't do it.

```latex
3^{301}~{\approx}~4.10674{\times}~10^{143}\text{.}
```

It should render as

$$3^{301}~{\approx}~4.10674{\times}~10^{143}\text{.}$$

But you do...

![1](https://github.com/jkriege2/JKQtPlotter/assets/11455533/67d94b9a-fb78-4bcf-a651-ae24889b1728)

**Comment by jkriege2** [comment]
Thanks for reporting ... I simply forgot to interpret a tilde as a special character ... it was treated as text ... should be a quick fix!

**Comment by jkriege2** [comment]
now renders as this:
![image](https://github.com/jkriege2/JKQtPlotter/assets/11967523/c02f2460-5d5c-4e44-8af7-eece744e1f8d)

**Comment by jkriege2** [comment]
fixed via https://github.com/jkriege2/JKQtPlotter/commit/c0bbe8f55719b01c23d29a94592f29a3722a0aba
