### ISSUE TITLE
Is this a correct way of licensing?

### ISSUE THREAD

**Issue by igormironchik** [jkriege2/JKQtPlotter#126]
Am I right that I can use a following license and copyright to the following files/folders/subfolders?

```
SPDX-FileCopyrightText: 2008-2024 Jan W. Krieger <jan@jkrieger.de>
SPDX-License-Identifier: LGPL-2.1-or-later
```

* appveyor.yml
* CODE_OF_CONDUCT.md
* JKQtPlotterAppveyorBuild.pro
* lib/\*
* readme.txt.in
* cmake/\*
* CONTRIBUTING.md
* JKQtPlotterBuildAllExamples.pro
* LICENSE
* SECURITY.md
* CMakeLists.txt
* Doxyfile
* JKQtPlotterBuildLibsOnly.pro
* README.md

**Comment by jkriege2** [comment]
Hi!

yes, for all of my code that's OK ... but there is a bit of third-party code (XITS/FIRA fonts) ... so if you compile them in and distribute them, you migt need to specify their license separately:

see https://jkriege2.github.io/JKQtPlotter/licensepage.html#extlicense_sec

the fonts are located below: https://github.com/jkriege2/JKQtPlotter/tree/master/lib/jkqtmathtext/resources

Hope that helps,
JAN

**Comment by igormironchik** [comment]
Yes, it helped. Thank you.
