### ISSUE TITLE
Fix for palette display

### ISSUE THREAD

**Issue by dtimson** [jkriege2/JKQtPlotter#13]
I've put in a PR for a fix to some problems with palette display - hope that's OK.

**Comment by jkriege2** [comment]
Hi ... yes I've seen it, but since I'm currently on holidays it will take a few days before I can review and merge ;-)

Anyways thanks for your contribution ... which is always much appreciated ...

Best, jan

**Comment by jkriege2** [comment]
I merged your contribution!

Thanks again!
JAN
