### ISSUE TITLE
Build Fails on Windows because of std::min

### ISSUE THREAD

**Issue by bilaljo** [jkriege2/JKQtPlotter#130]
On Windows, the build fails wherever `std::min` is used. The reason for this is that `std::min` is replaced by macro as long as you have included windows.h:

https://stackoverflow.com/questions/5004858/why-is-stdmin-failing-when-windows-h-is-included

Adding `#define NOMINMAX` wherever `windows.h` directly afterwards was included fixed it. I will post a PR as soon you have agreed to this approach.

**Comment by jkriege2** [comment]
Do go ahead ... happy to merge ... maybe though, it might be better to just define NOMINMAX in der CMake scripts globally?

**Comment by bilaljo** [comment]
That's actually an even more elegant idea (and robust against the future).

**Comment by bilaljo** [comment]
I fixed it accordingly in Compile Error on Windows fixed #131. It worked perfectly (I tested it).

**Comment by OgreTransporter** [comment]
There is also a second way to solve the problem and that is to use `std::min` with a data type e.g. `std::min<int>`.
