### ISSUE TITLE
A Bug under Release Mode

### ISSUE THREAD

**Issue by taibai123abc** [jkriege2/JKQtPlotter#134]
I use Visual Studio 2022 to run code. While run the `JKQTPDatastore* ds = ui->plot->getDatastore();` in Release mode, the VS throws an exception:  `0xC0000005: An access conflict occurred while reading location 0x0000000000001618.`. After that i debug the code in Release mode, and the VS show the error: `this->ui->plot->plotter is nullptr`. I am curious that in the construct method of JKQtPlotter, the plotter point has been initialized. So why this error occured?

**Comment by jkriege2** [comment]
Can you provide a code-snippet that reproduces this error?

Otherweise there is also a possibility, that an uncaught bad memory access somewhere else in your program causes this ... I haven't seen such an error so far, while using the lib ...

**Comment by taibai123abc** [comment]
I rebuild the JKQtPlotter recently. I use the command `cmake -G "Visual Studio 17 2022" "-DCMAKE_PREFIX_PATH=D:/Qt/6.5.3/msvc2019_64" "-DCMAKE_BUILD_TYPE=Debug" ..` and `cmake --build . --config "Debug" --target install` to build the library. While I run the example "User-Interactions in JKQtPlotter" in my compute in debug mode, the `plot->addGraph(graph1);` debug info shows that the plotter pointer of the plot is nullptr, and throw an exception. The pictures show the process of debug:
![image](https://github.com/user-attachments/assets/500d3947-f6c5-4713-b81a-b9cdf89bec48)
Press F11, and get:
![image](https://github.com/user-attachments/assets/26d2aedb-8d33-40d1-af90-03c7b49a026e)
Press F10, the get:
![image](https://github.com/user-attachments/assets/a7ed8786-f3da-481d-ab40-875cdfcdeccf)

**Comment by taibai123abc** [comment]
Because I rebuilt the library, I cannot reproduction the exception. But now, the program throws another exception like the following picture:
![image](https://github.com/user-attachments/assets/83ec983b-9591-4484-a69c-0fa30b5ba5da)

**Comment by taibai123abc** [comment]
Maybe it is a problem of my computer.

**Comment by taibai123abc** [comment]
Thanks for your response again.
