### ISSUE TITLE
how to draw electrocardiogram

### ISSUE THREAD

**Issue by robert-xiao** [jkriege2/JKQtPlotter#135]
how can the curve increases by one point per second，such like electrocardiogram

**Comment by jkriege2** [comment]
First you set up your graph and add two colums for x and y with the maximum number of entries.

You can simply add to the column that you use for drawing (or shift all data points one position to the left and then fill the new data point into the last bucket.

Then you can call JKQTPlotter::redrawPlot() to update the widget ... see https://jkriege2.github.io/JKQtPlotter/class_j_k_q_t_plotter.html#aebce042360ddc51b50472760ed272f7d

There are several examples that explain how to work with the datastore: https://jkriege2.github.io/JKQtPlotter/example_tutorial_projects.html#jkqtp_extut_datamanagement


I think this example
https://jkriege2.github.io/JKQtPlotter/_j_k_q_t_plotter_speed_test.html
Has code that shows what I described above

**Comment by 809185396** [comment]
Thank you for your answer。I have seen the example of speed, Mainly, my data is gradually increasing.

**Comment by jkriege2** [comment]
Either just let the column grow, by adding to it, or prefill with NaN. Then the data points should not be drawn.

**Comment by 809185396** [comment]
Thank you for your suggestion. I know how to do it now

**Comment by 809185396** [comment]
closed
