### ISSUE TITLE
JKQTPlotter ScribbleEvent Release/Last emitted signal not triggered when right clicked out of plot

### ISSUE THREAD

**Issue by Snolandia** [jkriege2/JKQtPlotter#137]
Per title, when clicking to drag, scribble event, if you right click while not in the plot, the last signal isnt emitted.

I fixed it in my fork by:

jkqtplotter.cpp
void JKQTPlotter::mousePressEvent(QMouse * event){
firstLine :     MouseDragAction prevAction = currentMouseDragAction;

// Then down at the portion of } else if (event->button()==Qt::RightButton){
// I added this portion

        if (prevAction.mode==jkqtpmdaScribbleForEvents){
          mouseDragRectXStart=plotter->p2x(event->pos().x()/magnification);
          mouseDragRectYStart=plotter->p2y((event->pos().y()-getPlotYOffset())/magnification);
          emit userScribbleClick(mouseDragRectXStart, mouseDragRectYStart, event->modifiers(), false, true);
          }

}

**Comment by jkriege2** [comment]
Could you post a Pull Request with your change?

**Comment by Snolandia** [comment]
https://github.com/jkriege2/JKQtPlotter/pull/139

**Comment by jkriege2** [comment]
merged. Thanks!
