### ISSUE TITLE
qt5.9 default in ubuntu 18.04 etc can be supported by changing the following

### ISSUE THREAD

**Issue by midjji** [jkriege2/JKQtPlotter#14]
from kk.front()  to kk.at(0)
in four places.

**Comment by jkriege2** [comment]
could you create a pull-request?

**Comment by midjji** [comment]
Would be good practice, I'll do that tomorrow. I have to say good work btw.
I've been looking for something like this for a while now, and it's damned
nice.

It would be just the .front fix though.

There is also a similar opencv bug. But I'm not touching that untill I
figure out what you intended to do.

Btw the cmake install does not work in linux. I rewrote the entire build
system to fix it, because as is, it is leaking flags all over the place and
not forwarding dependencies like it should, and not generating valid cmake
modules for the install. Should have a new version up and running tomorrow,
but can't test the windows variants. Modern cmake makes it much easier
though, so should be easy to fix.

**Comment by jkriege2** [comment]
I'm happy, the lib helps you ... and you like it :-)

Just open the PR and I will look into it.

About the CMake-build: That sounds interesting ... I'm not that experienced with it (basically I tried to lear, when doing the system for this lib) ... so any hints are welcome (if you should make a PR for that too, please make a second one, so we can discuss and test the stuff separately). If you make the PR, the CI-system should test the new build system on a windows platform too ... otherwise I'll have a look at it on my computer.

What's you OpenCV-problem? If you describe it, I can maybe explain ;-)

Best,
JAN

**Comment by midjji** [comment]
The basic opencv problem is that it does not compile with opencv trunk.

**Comment by midjji** [comment]
The opencv problem turned out to be simpler, its actually just that some
functions needed to be public instead of protected.
Why do you use JKQTCOMMON_LIB_EXPORT and set all visible?

**Comment by jkriege2** [comment]
The JKQTCOMMON_LIB_EXPORT is needed to add DLL export/import declspecs when building dynamic librraies on windows ... on linux it's simply defined as empty ...

About OpenCV: I think I fixed the problem with my last commit ... could you check whether it solves your problem? I think I didn't test the (optional) OpenCV-interface after cleaning up the datastore ...

**Comment by jkriege2** [comment]
Hi!

I reworked a bit the OpenCV-binding and examples and it should be fine now (for me it builds with OpenCV 4 and 3.4).

Also I removes the confusing compiler definitions you pointed out above ... as these were not used anyways.

Maybe I will look into the other stuff at a later time. But for now I think I will leave the CMake-System as is. Maybe I will add an alternative which allows to use this lib from another CMake project without first having to build and install it ... at least if I figure out how to pull that off properly ;-)

Best,
JAN

**Comment by midjji** [comment]
Thats great,

The last thing only requires that you make a Interface target which depends
on the three libs. That's it.

Add_library( jktplotter Interface)

Target_link_libraries(jktplotter liba) ...

And then use by add subdirectory.  Its all in the fork.

**Comment by jkriege2** [comment]
I think this is mostly solved ... so I will close it. Please reopen, if I missed anything!
