### ISSUE TITLE
Lot of errors of the type "##SEARCHING  ";" : DIDN'T FIND!"

### ISSUE THREAD

**Issue by certik** [jkriege2/JKQtPlotter#17]
When running most examples, for example the "ui" one, there are lots of errors printed into the terminal of the type:
```
##SEARCHING  ";"
##SEARCHING  ";" : SEARCHING IN  "XITS"  [unicode]
##SEARCHING  ";" : SEARCHING IN  "XITS"  [winSym]
##SEARCHING  ";" : DIDN'T FIND!
```
What does that mean? How can one fix that?

I use Ubuntu 18.04.

**Comment by jkriege2** [comment]
Thanks for noting ... these were some left-over debug-message, which I removed in my last commit.

Best,
JAN

**Comment by certik** [comment]
Thanks @jkriege2, I just tested it and it's fixed!
