### ISSUE TITLE
CMake files not automatically picked up

### ISSUE THREAD

**Issue by certik** [jkriege2/JKQtPlotter#18]
I install JKQtPlotter using:
```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$HOME/ext/jkqtplotter/ ..
make
make install
```
Then when building my application, my CMakeLists.txt contains:
```
# Qt
find_package(Qt5 COMPONENTS Core Widgets PrintSupport Svg Xml REQUIRED)

# JKQtPlotter
find_package(JKQTCommonLib REQUIRED)
find_package(JKQTMathTextLib REQUIRED)
find_package(JKQTPlotterLib REQUIRED)
```

The way it should be possible to build my application is:
```
cmake -DCMAKE_PREFIX_PATH=$HOME/ext/jkqtplotter/ .
```
But it fails to find the JKQtPlotter cmake files. Instead, one must do:
```
cmake -DCMAKE_PREFIX_PATH=$HOME/ext/jkqtplotter/lib/cmake .
```
Then everything works.

By looking at how other libraries do that, they seem to put the cmake files into `$PREFIX/lib/cmake/JKQTCommonLib/`. When I manually create `lib/cmake/JKQTCommonLib` and move the files there, then cmake automatically finds them. It fails because some paths are not adjusted correctly, but it shows how to fix this problem. One also has to create directories `JKQTMathTextLib` and `JKQTPlotterLib`.

What I don't know is how to modify the CMake build system in JKQtPlotter to do this automatically.

Note: I actually create a Conda environment and install JKQtPlotter into it. CMake picks up any library out of the box from the Conda environment, except JKQtPlotter due to the problem I reported above. It would be really nice to fix this so that things work out of the box.

**Comment by jkriege2** [comment]
Hi!

I reworked the CMake build system a bit ... could you have a look whether this works better for you?

Best,
JAN

**Comment by certik** [comment]
I tested it and it works! Thank you for fixing it, I really appreciate it. Note that I had to modify my CMakeLists.txt, now it has:
```cmake
find_package(JKQTCommonSharedLib REQUIRED)
find_package(JKQTMathTextSharedLib REQUIRED)
find_package(JKQTPlotterSharedLib REQUIRED)
...
target_link_libraries(my_application JKQTPlotterSharedLib)
```
