### ISSUE TITLE
Some qustion about JKQTmathText

### ISSUE THREAD

**Issue by srazi** [jkriege2/JKQtPlotter#2]
1. Is there a way to know how good a LaTeX string was parsed? Maybe something like `count of unknown symbols`?

2. I want to draw LaTeX string to a pixmap as small as it can be. Is calling `JKQTmathText::getSize(painter)` the fatest way? (Does `getSize()` really use painter? I see it is not used in some nodes.)

3. Is `JKQTmathText::draw()` fast enough or I should cache the resulting pixmap?

**Comment by jkriege2** [comment]
ad 1: no ... never added something like that

ad 2: Yes it's the right way and yes the painter is needed to construct `QFontMetricsF` instances.

ad 3: Depends ... drawing the LaTeX fragment can take several 10s to 100s milliseconds (depending on many factros, like anti-aliasing, complexity, ...). I updated [test/jkqtmathtext_test](https://github.com/jkriege2/JKQtPlotter/tree/master/test/jkqtmathtext_test) to also display parse and render-times. Also it allows to render a user-defined string (selected the last testitem, enter a string in the Latex source firld and press "Render")

Best,
JAN

**Comment by srazi** [comment]
> ad 1: no ... never added something like that

Can you give me some hint to implement something like that?

> ad 3: Depends ... drawing the LaTeX fragment can take several 10s to 100s milliseconds (depending on many factros, like anti-aliasing, complexity, ...). I updated test/jkqtmathtext_test to also display parse and render-times. Also it allows to render a user-defined string (selected the last testitem, enter a string in the Latex source firld and press "Render")

Thanks for update. I will send some screenshot about two rendering bugs.

**Comment by jkriege2** [comment]
ad 1: Some time since I wrote this code ... but I found one error reporting facility (during parsing stage): You can get a list of parse-errors via `get_error_list()`, which returns a QStringList with errors, but I think that does not e.g. check whether a symbol is known or not ... it reports errors like a second argument for `\frac` is missing and such ... maybe that helps?
To report on unknown symbols/instructions, you could add code to the constructors of the nodes (e.g. of `JKQTmathText::MTsymbolNode`) that adds an error to the base classes `error_list` when a name is not found in the symbol maps/hashmaps

ad2: Thanks for reporting ... has been fixed.

**Comment by jkriege2** [comment]
PS: Will you only use the LaTeX renderer, or also the plotting lib?

**Comment by srazi** [comment]
> ad 1: Some time since I wrote this code ... but I found one error reporting facility (during parsing stage): You can get a list of parse-errors via get_error_list(), which returns a QStringList with errors, but I think that does not e.g. check whether a symbol is known or not ... it reports errors like a second argument for \frac is missing and such ... maybe that helps?
To report on unknown symbols/instructions, you could add code to the constructors of the nodes (e.g. of JKQTmathText::MTsymbolNode) that adds an error to the base classes error_list when a name is not found in the symbol maps/hashmaps

Thanks. I will check it.

> ad2: Thanks for reporting ... has been fixed.

Great!

> PS: Will you only use the LaTeX renderer, or also the plotting lib?

Certainly, I will not use the plotting lib in near future. I am wrinting a LaTeX editor that it will have some rendering modes. As one of them I want to use your LaTeX rendering project (hmm... unfortunatly, it's closed source at this stage, I hope you don't mine).

**Comment by jkriege2** [comment]
About closed source: That's simple: My code is LGPL-licensed, so you may use it, as long as you publish any alterations, that you do to the parser. You don't have to publish your code.

**Comment by srazi** [comment]
> About closed source: That's simple: My code is LGPL-licensed, so you may use it, as long as you publish any alterations, that you do to the parser. You don't have to publish your code.

Yeah, thanks.
