### ISSUE TITLE
The CI does not seem to be testing Linux and macOS

### ISSUE THREAD

**Issue by certik** [jkriege2/JKQtPlotter#23]
The Travis CI only seems to be testing doxygen.

@jkriege2 would you be against testing every PR on Linux, macOS and Windows? That would prevent the issues I found in #19 and #20.

I am happy to contribute the CI improvements.

**Comment by jkriege2** [comment]
Just provide a PR for these additional builds and I will have a look at them ;-)

**Comment by certik** [comment]
Ok, I am working on it in #26. I will ping you once it is ready for review.

**Comment by jkriege2** [comment]
Pr has been merged
