### ISSUE TITLE
LaTeX rendering issue in $...$ mode

### ISSUE THREAD

**Issue by srazi** [jkriege2/JKQtPlotter#3]
`$\leq$` and `$\in$` using  jkqtmathtext_test tool:

![leq](https://user-images.githubusercontent.com/1328454/49553431-e3b4c980-f90c-11e8-8b4e-e5d0bb05d21b.png)

![in](https://user-images.githubusercontent.com/1328454/49553442-eca59b00-f90c-11e8-8e16-132b9846e8d7.PNG)

**Comment by jkriege2** [comment]
fixed via https://github.com/jkriege2/JKQtPlotter/commit/a02d7ea3d2d5c8acbb0cd485aa5d136547c16b0b

**Comment by jkriege2** [comment]
thanks for reporting!

**Comment by srazi** [comment]
Indeed, the first test string that you added in recent commit, breaks here for me:
![image](https://user-images.githubusercontent.com/1328454/49610042-9b4fe700-f9b2-11e8-9f53-a44f5595404c.png)

Another example is `$T:X\to Y$`. In all cases no-dollar mode works perfect :+1:  .

**Comment by jkriege2** [comment]
I will have a look into that issue

**Comment by jkriege2** [comment]
Should be fixed by this: https://github.com/jkriege2/JKQtPlotter/commit/367c1455a00a66fe165484a82e13f02a35fda69f

**Comment by srazi** [comment]
Great, thanks. I tested it with some different files containing lots of inline formulas and all formulas (including those with unknown symbols or commands) were rendered correctly.
