### ISSUE TITLE
slow startup (QFontDatabase?)

### ISSUE THREAD

**Issue by eudoxos** [jkriege2/JKQtPlotter#31]
Hi, thank you for your great library which I enjoy using for the first time very much! I have some issues, I am not sure whether it is my lack of experience with the internals.

The most acute one is that JKQtPlotter is apparently scanning the whole system for all installed fonts and it takes lots of time. On my workstation (which has 64GB RAM, used mostly for disk cache, thus no actual disk access is entailed) this takes 10 seconds (full installatoin of TeXLive and several extra font packs); this is what strace is showing during those 10s:
```
...
openat(AT_FDCWD, "/usr/share/fonts/truetype/larabie/duality_.ttf", O_RDONLY) = 23
fcntl(23, F_SETFD, FD_CLOEXEC)          = 0
fstat(23, {st_mode=S_IFREG|0644, st_size=49276, ...}) = 0
mmap(NULL, 49276, PROT_READ, MAP_PRIVATE, 23, 0) = 0x7fedf0338000
close(23)                               = 0
openat(AT_FDCWD, "/usr/share/fonts/truetype/larabie/dyspepsi.ttf", O_RDONLY) = 23
fcntl(23, F_SETFD, FD_CLOEXEC)          = 0
fstat(23, {st_mode=S_IFREG|0644, st_size=43308, ...}) = 0
mmap(NULL, 43308, PROT_READ, MAP_PRIVATE, 23, 0) = 0x7fedf032d000
close(23)                               = 0
...
```
Would it be possible to avoid this? I would be fine building without the math rendering library -- currently there is no option for that in cmake, could I help adding such option perhaps? Maybe you have some other pro tip :)

Thanks!

**Comment by jkriege2** [comment]
Hi!

hmmm ... building without the math rendering is not possible (at least not without a lot of work) as it is tightly integrated into the library itself.

I could have a look at the constructor of JKQTMathText::JKQTMathText() ... it scans the QFontDatabase to find suitable fonts on the system ... maybe that can be switched off by a compiler-flag ... could you please check whether the time is spent in JKQTMathText::JKQTMathText() or in JKQTMathText::useXITS(), JKQTMathText::useSTIX(), JKQTMathText::useASANA()?

Best,
JAN

**Comment by jkriege2** [comment]
I checked on my computer and I have 201  fonts installed. A Debug-Build needs about  305ms to iterate of all these fonts ...

**Comment by jkriege2** [comment]
I removed the (frankly unnecessary) iteration from the contructor with https://github.com/jkriege2/JKQtPlotter/commit/97a1780b3d6f759fc0cb40f4f63c37673765c0f2 ... This should fix the issue!

**Comment by eudoxos** [comment]
> I checked on my computer and I have 201 fonts installed. A Debug-Build needs about 305ms to iterate of all these fonts ...
I get `fc-list|wc -l` → `2779`. Will test the fixed version soon, thanks!

**Comment by jkriege2** [comment]
seen it ... should be fixed now

**Comment by eudoxos** [comment]
Perfect, startup is instantaneous now :) Thanks!

**Comment by jkriege2** [comment]
rendering quality of OK for you?

**Comment by eudoxos** [comment]
No problems seen.
