### ISSUE TITLE
Slow rendering

### ISSUE THREAD

**Issue by certik** [jkriege2/JKQtPlotter#32]
Here is how I call JKQtPlotter:
```c++
QVector<double> fromCArray(const double *x, size_t len)
{
    QVector<double> Y;
    Y.reserve(len);
    Y.resize(len);
    std::memcpy(Y.data(), x, len * sizeof(double));
    return Y;
}

void MainWindow::plot(const std::vector<double> &R,
                      const std::vector<double> &T,
                      const std::vector<double> &P)
{
    size_t step = T.size()/10;
    if (step == 0) step = 1;
    JKQTPDatastore* ds=ui->plot->getDatastore();
    ui->plot->clearGraphs(true);
    for (size_t i=0; i < T.size()-1; i += step) {
        QVector<double> X, Y;
        X = QVector<double>::fromStdVector(R);
        Y = fromCArray(&P[i*R.size()], R.size());
        graph = new JKQTPXYLineGraph(ui->plot);
        size_t columnX=ds->addCopiedColumn(X, "x");
        size_t columnY=ds->addCopiedColumn(Y, "y");
        graph->setXColumn(columnX);
        graph->setYColumn(columnY);
        graph->setSymbolType(JKQTPNoSymbol);
        ui->plot->addGraph(graph);
    }
    ui->plot->getXAxis()->setLogAxis(true);
    ui->plot->getYAxis()->setLogAxis(true);
    ui->plot->getXAxis()->setAxisLabel("Density [g / cm$^3$]");
    ui->plot->getYAxis()->setAxisLabel("Pressure [GPa]");
    ui->plot->getXAxis()->setTickLabelFontSize(14);
    ui->plot->getYAxis()->setTickLabelFontSize(14);
    ui->plot->getXAxis()->setLabelFontSize(14);
    ui->plot->getYAxis()->setLabelFontSize(14);
    ui->plot->zoomToFit();
}
```
And it takes about 0.5s to render. That seems really slow. @jkriege2 do you see any obvious inefficiency? I can see that the data is first copied from `std::vector` to `QVector` and then copied again (I assume) into `JKQTPDatastore`. Otherwise is this how JKQtPlotter should be used?

**Comment by jkriege2** [comment]
Hi!

I don't completely understand, how the plot should look ... but I think I can give you some hints:

1. You don't need to copy std::vector --> QVector --> Datastore ... The Datastore has several functions that allow to directly copy (or even just reference, if you outside datastorage ist stable, i.e. has stable adresses) external data in different forms: 
    - http://jkriege2.github.io/JKQtPlotter/_j_k_q_t_plotter_basic_j_k_q_t_p_datastore.html
    - http://jkriege2.github.io/JKQtPlotter/_j_k_q_t_plotter_basic_j_k_q_t_p_datastore_iterators.html
Using one of these should save you some time.
2. You can save some replotting time if you call JKQtPlotter::setPlotUpdateEnabled(false); before editing the plot and then JKQtPlotter::setPlotUpdateEnabled(true); and finally JKQtPlotter::redrawPlot(); This prevents a redraw, which is done every time you change a property or add a graph.
3. A question: You are adding T.size()/10 graphs ... are they all different, or how should the final graph look? Maybe here is some more potential for optimization
4. Have a look at the following page for details on the plotting speed: http://jkriege2.github.io/JKQtPlotter/_j_k_q_t_plotter_speed_test.html

Hope that helps,
JAN

**Comment by certik** [comment]
@jkriege2 thanks a lot for the tips! I implemented 1., and it's 2. that made a huge difference. Now the plot is almost instantaneous. Here is the new code:
```c++
void MainWindow::plot(const std::vector<double> &R,
                      const std::vector<double> &T,
                      const std::vector<double> &P)
{
    size_t step = T.size()/10;
    if (step == 0) step = 1;
    JKQTPDatastore* ds=ui->plot->getDatastore();
    ui->plot->setPlotUpdateEnabled(false);
    ui->plot->clearGraphs(true);
    for (size_t i=0; i < T.size()-1; i += step) {
        graph = new JKQTPXYLineGraph(ui->plot);
        graph->setXColumn(ds->addColumn(const_cast<double*>(&R[0]),
                    R.size(), "x"));
        graph->setYColumn(ds->addColumn(const_cast<double*>(&P[i*R.size()]),
                    R.size(), "y"));
        graph->setSymbolType(JKQTPNoSymbol);
        ui->plot->addGraph(graph);
    }
    ui->plot->getXAxis()->setLogAxis(true);
    ui->plot->getYAxis()->setLogAxis(true);
    ui->plot->getXAxis()->setAxisLabel("Density [g / cm$^3$]");
    ui->plot->getYAxis()->setAxisLabel("Pressure [GPa]");
    ui->plot->getXAxis()->setTickLabelFontSize(14);
    ui->plot->getYAxis()->setTickLabelFontSize(14);
    ui->plot->getXAxis()->setLabelFontSize(14);
    ui->plot->getYAxis()->setLabelFontSize(14);
    ui->plot->zoomToFit();
    ui->plot->setPlotUpdateEnabled(true);
    ui->plot->redrawPlot();
}
```
Here is an example of how the plot looks like:

![example](https://user-images.githubusercontent.com/20568/69651462-5989d780-102d-11ea-83e2-10f59f8ffe53.png)

Another issue is that the label 1000 on the X-axis is cropped in the Qt GUI, because it goes outside of the plotting area. But that's a separate issue.

Thank you for your help with this, I am happy with the performance now.
