### ISSUE TITLE
Make a new release

### ISSUE THREAD

**Issue by certik** [jkriege2/JKQtPlotter#36]
Now when JKQtPlotter is in Conda (https://github.com/conda-forge/jkqtplotter-feedstock) would you mind tagging a new release please? Currently the latest release, which is used by Conda, does not include #34.

**Comment by certik** [comment]
@jkriege2 let me know if or how I can help with this in any way.

**Comment by jkriege2** [comment]
Hi!

I will do this on the weekend ... sorry I'm quite busy at the moment project deadlines and all ;-)

Best,
JAN

**Comment by certik** [comment]
No worries. Thanks!

**Comment by jkriege2** [comment]
here you go: https://github.com/jkriege2/JKQtPlotter/releases/tag/v2019.11.1

Best,
JAN

**Comment by certik** [comment]
Thank you! I updated the Conda package: https://github.com/conda-forge/jkqtplotter-feedstock/pull/2
