### ISSUE TITLE
CMake installs things into $PREFIX/doc/*.txt

### ISSUE THREAD

**Issue by certik** [jkriege2/JKQtPlotter#37]
So one must remove it by hand, e.g. (https://github.com/conda-forge/jkqtplotter-feedstock/blob/6cedd9980147f56054759cb2d6c30a8145c28d3a/recipe/build.sh#L12):
```
rm $PREFIX/doc/_Readme.txt
rm $PREFIX/doc/_LICENSE.txt
rm $PREFIX/doc/_XITS_LICENSE.txt
rm $PREFIX/doc/_XITS_README.md
```
One should instead install it into `$PREFIX/doc/JKQtPlotter`.

**Comment by jkriege2** [comment]
thanks for reporting.

should be fixed by https://github.com/jkriege2/JKQtPlotter/commit/04219ec6d9dfd81a47702c279e0fc6ee4d1efbaa

Best,
JAN
