### ISSUE TITLE
Build error when JKQtPlotter_BUILD_INCLUDE_XITS_FONTS set to OFF

### ISSUE THREAD

**Issue by smistad** [jkriege2/JKQtPlotter#41]
Turning off the cmake option JKQtPlotter_BUILD_INCLUDE_XITS_FONTS causes the following error on windows (MSVC 2019, Qt 5.14):
```
jkqtmathtext.obj : error LNK2019: unresolved external symbol "int __cdecl qInitResources_xits(void)" (?qInitResources_xits@@YAHXZ) referenced in function "public: __cdecl JKQTMathText::JKQTMathText(class QObject *)" (??0JKQTMathText@@QEAA@PEAVQObject@@@Z)
```

Most likely caused by the following line in jkqtmathtext.cpp: 
```C++
Q_INIT_RESOURCE(xits);
```

**Comment by jkriege2** [comment]
Thanks for reporting and sorry for the long wait time ... I fixed the bug with https://github.com/jkriege2/JKQtPlotter/commit/f6505e35fce3948284bbbd262f70765ced008489.

best,
JAN
