### ISSUE TITLE
plot3d capabilities ?

### ISSUE THREAD

**Issue by Nelson-numerical-software** [jkriege2/JKQtPlotter#42]
Hi,

Can we do this with JKQtPlotter ?
![image](https://user-images.githubusercontent.com/23081266/83395634-f1141c80-a3fa-11ea-8cfb-694bceb142f0.png)

**Comment by jkriege2** [comment]
Unfortunately there is no 3D plotting capability in JKQtPlotter ... and currently I don't have plans to add it. Note that the complete backend of JKQTPlotter is designed for 2D plotting only.

You can do a flat image plot though ... see e.g. http://jkriege2.github.io/JKQtPlotter/_j_k_q_t_plotter_image_plot.html

Best,
JAN
