### ISSUE TITLE
Incorrect tag in .ini style files

### ISSUE THREAD

**Issue by smistad** [jkriege2/JKQtPlotter#49]
The example .ini style files have the tag [plot] https://github.com/jkriege2/JKQtPlotter/tree/master/lib/jkqtplotter/resources/styles

However, the JKQTPGetSystemDefaultStyle().loadSettings() methods' default tag is [plots], not [plot].

**Comment by jkriege2** [comment]
fixed via https://github.com/jkriege2/JKQtPlotter/issues/49
