### ISSUE TITLE
Is there away to point the JKQTPDatastoreItem to user data other then double[]

### ISSUE THREAD

**Issue by ashley-b** [jkriege2/JKQtPlotter#53]
Not sure if Iam missing some thing, but Iam piloting very large data sets of float's and can't afford to transform the data as it will use to much memory. The JKQTPDatastore class is nice, but it only seams to operate on double's far as I understand.

Thanks

**Comment by jkriege2** [comment]
Hi!

JKQTPDatastore uses doubles internally to manage the data. This makes plotting faster (and the code a bit simpler), as we do not have to check for the datatype when accessing the data for each plot point.

You can use the templated feamily of addCopiedColumn()-functions to copy the data into the internal store.

**Comment by ashley-b** [comment]
Thanks for the feedback and the great library.

As I mention the data sets being plotted is very large and being memory mapped from a file to save on memory usage, so can't really copy it with out using a lot of memory.
I might look into overriding the draw function and plot it manually.

Thanks

**Comment by jkriege2** [comment]
The online exception are some if the Image plotting classes. These allow to provide a pointer to memory Arrays of different types. If you want to override draw() maybe you can reuse soweit
