### ISSUE TITLE
Logscale zoom multiple zeros?

### ISSUE THREAD

**Issue by sufuk** [jkriege2/JKQtPlotter#56]
Hi I ran into a problem.

In logscale if the values are so small there is couple of 0 values shown more than once in Y axis like that how to avoid that? Also if you doo zoom operations it can be more or less zeros.
![23](https://user-images.githubusercontent.com/32745693/131094948-58c36062-ff42-4d2d-ae27-bf5db89a0dcc.png)

**Comment by jkriege2** [comment]
I can confirm this bug ... anf it is fixed via https://github.com/jkriege2/JKQtPlotter/issues/56
