### ISSUE TITLE
Compile Error,Qt5.12.11+MSVC2019

### ISSUE THREAD

**Issue by libaineu2004** [jkriege2/JKQtPlotter#58]
jkqtpmathparser.obj:-1: error: LNK2019: 无法解析的外部符号 "public: __cdecl JKQTPMathParser::jkmpResult::jkmpResult(void)" (??0jkmpResult@JKQTPMathParser@@QEAA@XZ)，函数 "struct JKQTPMathParser::jkmpResult __cdecl `anonymous namespace'::fFloatToStr(struct JKQTPMathParser::jkmpResult *,unsigned char,class JKQTPMathParser *)" (?fFloatToStr@?A0x48c32274@@YA?AUjkmpResult@JKQTPMathParser@@PEAU23@EPEAV3@@Z) 中引用了该符号

jkqtpimagergb.obj:-1: error: LNK2001: 无法解析的外部符号 "public: virtual __cdecl JKQTPSaveDataAdapter::~JKQTPSaveDataAdapter(void)" (??1JKQTPSaveDataAdapter@@UEAA@XZ)

moc_jkqtplotter.obj:-1: error: LNK2001: 无法解析的外部符号 "public: virtual class QPaintDevice * __cdecl JKQTPPaintDeviceAdapter::createPaintdeviceMM(class QString const &,double,double)const " (?createPaintdeviceMM@JKQTPPaintDeviceAdapter@@UEBAPEAVQPaintDevice@@AEBVQString@@NN@Z)

jkqtplotterlib_debug.lib(jkqtplotter.obj):-1: error: LNK2019: 无法解析的外部符号 "public: void __cdecl JKQTBasePlotter::drawNonGrid(class JKQTPEnhancedPainter &,class QPoint const &)" (?drawNonGrid@JKQTBasePlotter@@QEAAXAEAVJKQTPEnhancedPainter@@AEBVQPoint@@@Z)，函数 "public: void __cdecl JKQTPlotter::redrawPlot(void)" (?redrawPlot@JKQTPlotter@@QEAAXXZ) 中引用了该符号

jkqtplotterlib_debug.lib(jkqtpgraphsbaseerrors.obj):-1: error: LNK2019: 无法解析的外部符号 "public: enum Qt::PenStyle __cdecl JKQTBasePlotter::JKQTPPen::errorStyle(void)const " (?errorStyle@JKQTPPen@JKQTBasePlotter@@QEBA?AW4PenStyle@Qt@@XZ)，函数 "public: void __cdecl JKQTPGraphErrorStyleMixin::initErrorStyle(class JKQTBasePlotter *,int &,enum JKQTPPlotStyleType)" (?initErrorStyle@JKQTPGraphErrorStyleMixin@@QEAAXPEAVJKQTBasePlotter@@AEAHW4JKQTPPlotStyleType@@@Z) 中引用了该符号

**Comment by jkriege2** [comment]
Do you use qmake or cmake? 

Please try again with the current MASTER and cmake ...

**Comment by jkriege2** [comment]
JKQtPlotter was not compatible with Qt 5.15 ... now it is. So please try again! I don't see any problems with MSVC ... if the problems persist, please reopen this Issue!
