### ISSUE TITLE
Android Build Problem

### ISSUE THREAD

**Issue by sufuk** [jkriege2/JKQtPlotter#59]
Hello I wanna use JKQTplotter but just the jkqtmathtext in y android application I can build it for x86_64 & x86 platforms but it gives error in armeabi-v7a and arm64-v8a:

I use opencv for android btw.
armeabi-v7a CMake command: 
`-DCMAKE_TOOLCHAIN_FILE="/home/sufuk/Android/Sdk/ndk/21.4.7075529/build/cmake/android.toolchain.cmake" -DANDROID_ABI="armeabi-v7a" -DANDROID_PLATFORM="android-27" -DQt5_DIR="/home/sufuk/Qt/5.15.2/android/lib/cmake/Qt5"  -DOpenCV_DIR=/opt/OpenCV-android-sdk/sdk/native/jni/ -DCMAKE_INSTALL_PREFIX="/opt/JKQTPlotter/android" -DCMAKE_BUILD_TYPE="Release"`

It gives an error after loading cmake:
`error: unknown target CPU 'armv7-a'`

arm64-v8a CMake command: 
`-DCMAKE_TOOLCHAIN_FILE="/home/sufuk/Android/Sdk/ndk/21.4.7075529/build/cmake/android.toolchain.cmake" -DANDROID_ABI="arm64-v8a" -DANDROID_PLATFORM="android-27" -DQt5_DIR="/home/sufuk/Qt/5.15.2/android/lib/cmake/Qt5"  -DOpenCV_DIR=/opt/OpenCV-android-sdk/sdk/native/jni/ -DCMAKE_INSTALL_PREFIX="/opt/JKQTPlotter/android" -DCMAKE_BUILD_TYPE="Release"`

It gives an error after build:
`/home/sufuk/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libGLESv2.so, needed by /home/sufuk/Qt/5.15.2/android/lib/libQt5Svg_arm64-v8a.so, not found (try using -rpath or -rpath-link)
/home/sufuk/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libz.so, needed by /home/sufuk/Qt/5.15.2/android/lib/libQt5Svg_arm64-v8a.so, not found (try using -rpath or -rpath-link)
/home/sufuk/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: liblog.so, needed by /home/sufuk/Qt/5.15.2/android/lib/libQt5Svg_arm64-v8a.so, not found (try using -rpath or -rpath-link)
/home/sufuk/Android/Sdk/ndk/21.4.7075529/toolchains/llvm/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libc++_shared.so, needed by /home/sufuk/Qt/5.15.2/android/lib/libQt5Svg_arm64-v8a.so, not found (try using -rpath or -rpath-link)
/home/sufuk/Qt/5.15.2/android/lib/libQt5Gui_arm64-v8a.so: undefined reference to deflateInit_`

Why it compiles for x86 & x86_64 but not others thank you very much need help I wanna use in my graduation project.

**Comment by jkriege2** [comment]
Hi!
I have zero experience with Android (other than as a user ;-) ... so I cannot really help you with this.
Also I never tested the lib for Android, so you might be the first ;-)

The only thing, I can think of: As you get a CMake error that the architecture armv7-a is not recognized ... do you use a current/matching CMake-Version? Is that ARM-Architecture defined in that CMake version?

Maybe this bit from the Documentation of CMake helps:
https://cmake.org/cmake/help/v3.4/prop_tgt/ANDROID_ARCH.html

Best,
JAN

**Comment by jkriege2** [comment]
PS: If you get it to compile and need some changes in the CMake-files, it would be great if you could push them as PR ...

**Comment by sufuk** [comment]
> Hi! I have zero experience with Android (other than as a user ;-) ... so I cannot really help you with this. Also I never tested the lib for Android, so you might be the first ;-)
> 
> The only thing, I can think of: As you get a CMake error that the architecture armv7-a is not recognized ... do you use a current/matching CMake-Version? Is that ARM-Architecture defined in that CMake version?
> 
> Maybe this bit from the Documentation of CMake helps: https://cmake.org/cmake/help/v3.4/prop_tgt/ANDROID_ARCH.html
> 
> Best, JAN

I will look at that thank you,


> PS: If you get it to compile and need some changes in the CMake-files, it would be great if you could push them as PR ...

Okey I will do that,
Also I tested JKQtMathText in x86_64 android it works perfectly.

**Comment by jkriege2** [comment]
please open a PR, when you fixed this ... currently I'm not intending to actively support Android, although fixes in that direction are welcome by all means!
