### ISSUE TITLE
Intalling JKQTPlotter on Ubuntu 20.04 & QtCreator 6.0.1

### ISSUE THREAD

**Issue by PeakDesign** [jkriege2/JKQtPlotter#60]
Hello jkriege2. I'm a bit of a Qt/linux newbie, but now managing to find my way around. I'd love to use JKQTPlotter in several projects I have using the Qt UI system, but have not managed to follow your instructions.
My system:Qt Creator 6.0.1 Based on Qt 6.2.2 (GCC 10.3.1 20210422 (Red Hat 10.3.1-1), 64 bit) Built on Dec 15 2021 08:27:24
Using Qt 5.15.2 with GCC:
![image](https://user-images.githubusercontent.com/68291842/149942080-a4651c23-9eb3-4f3d-95ca-8425dc92895b.png)
I have downloaded  JKQTPlotter to /home/john/JKQTPlotter, and opened the file JKQTPlotter-BuildAllExamples.pro in QtCreator. On building it, I get a lot of errors about cannot find -ljkqtplotterlib_debug.
I don't see the built library files in the /lib or /qmake/staticlib folders.
I've tried various combinations of building the individual example projects (with & without building the lib), or building the qmake/staticlib/jkqtplotterlib/jkqtplotterlib.pro (again in QtCreator), with no more success.
Is this an issue with QtCreator 6 - I note a previous comment that this wasn't supported yet?
Or is there an obvious installation step I've missed out?
Thanks for any pointers - your package does look very much what I'm looking for.
John

**Comment by jkriege2** [comment]
please try the CMake build system ... does it work for you with that?

**Comment by jkriege2** [comment]
BTW: Qt6 support was added recently ... so please try again!

**Comment by jkriege2** [comment]
I tested the QMake-Build-System on windows: For me it works ...

**Comment by jkriege2** [comment]
closing, because it seems abandoned and should be fixed + qmake is more or less deprecated anyways!
