### ISSUE TITLE
Compile the library with Qt5.15 or Qt6

### ISSUE THREAD

**Issue by sim186** [jkriege2/JKQtPlotter#61]
Someone get it compile with Qt5.15 or Qt6?

I'm trying to understand if I can fix it on my own, but if someone already make it work would be great!

**Comment by jkriege2** [comment]
On Qt 5.15 itt should work now ... Qt6 will be tackled next ;-)

**Comment by jkriege2** [comment]
it is now compatible with Qt 5.15 AND Qt6

**Comment by jkriege2** [comment]
fixed via https://github.com/jkriege2/JKQtPlotter/pull/66

**Comment by sim186** [comment]
Thanks a lot!
