### ISSUE TITLE
Can the pixel in heatmap be smooth one?

### ISSUE THREAD

**Issue by xichaoqiang** [jkriege2/JKQtPlotter#67]
![image](https://user-images.githubusercontent.com/30900789/164999583-46410d73-b466-4037-86ed-e77701a5c79d.png)
Can the heatmap use following smooth options?

![image](https://user-images.githubusercontent.com/30900789/164999621-35864771-219b-44c1-bce9-caf6e5835d0b.png)

**Comment by jkriege2** [comment]
Hi!
No, Not directly in the library. But you could apply the appropriate filter to your data, before plotting it. JKQtPlotter has Bindings to CImg (very lightweight, header only) and OpenCV ... in both you should be able to do the smoothing ...

Would that solve your problem?

Best,
Jan

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.
I will try as your suggestion.
