### ISSUE TITLE
Can JKQtPlotter plot wiggle plot?

### ISSUE THREAD

**Issue by xichaoqiang** [jkriege2/JKQtPlotter#68]
Here is a demo of wiggle plot.

Can JKQtPlotter plot wiggle plot?

![image](https://user-images.githubusercontent.com/30900789/164999748-46c7b3ad-3aee-4687-81c6-3509e02d7eae.png)

**Comment by jkriege2** [comment]
You can do a filled curve plot:
https://jkriege2.github.io/JKQtPlotter/_j_k_q_t_plotter_filled_graphs.html

.. but single color only (at the moment) ...

Use 
https://jkriege2.github.io/JKQtPlotter/class_j_k_q_t_p_filled_curve_x_graph.html
Or in your case
https://jkriege2.github.io/JKQtPlotter/class_j_k_q_t_p_filled_curve_y_graph.html

**Comment by xichaoqiang** [comment]
Thanks for your kindly reply.

**Comment by jkriege2** [comment]
implemented feature "wiggle plots" in https://github.com/jkriege2/JKQtPlotter/commit/ee2477a1f6ce05776ba0e1ef1777e17830122c35 ... please have a look at the example https://github.com/jkriege2/JKQtPlotter/tree/master/examples/wiggleplots
