### ISSUE TITLE
Show data tooltip on MouseMove

### ISSUE THREAD

**Issue by sim186** [jkriege2/JKQtPlotter#69]
Hi,

first of all thanks for your amazing job into JKQtplotter. I would like to show the tooltip instead on the drag or the click action, on the mouse move event. Basically while hovering one datapoint. Can you address me how to achive this task?

Thanks!

**Comment by jkriege2** [comment]
Hi!

this is not possible right now ... but I'm working on a solution ...

Best,
JAN

**Comment by jkriege2** [comment]
feature implemented in https://github.com/jkriege2/JKQtPlotter/commit/ae5713ea68c34d5d1df09ad9df688763d0c1a46a

Hope it works four you now ... you can activate the feature using the context menu/toolbar, or by calling JKQtPlotter::registerMouseMoveAction()

**Comment by sim186** [comment]
> feature implemented in [ae5713e](https://github.com/jkriege2/JKQtPlotter/commit/ae5713ea68c34d5d1df09ad9df688763d0c1a46a)
> 
> Hope it works four you now ... you can activate the feature using the context menu/toolbar, or by calling JKQtPlotter::registerMouseMoveAction()

Wow..amazing! Thank you, I will update the library and I will let you know as soon as possible!

**Comment by sim186** [comment]
Thanks for this, I tried and worked out really well. I will enclose a screenshot soon. 👍
