### ISSUE TITLE
Possible typo in jkqtplotter/CMakeLists.txt

### ISSUE THREAD

**Issue by tedlinlab** [jkriege2/JKQtPlotter#70]
I think there is a typo in jkqtplotter/CMakeLists.txt

Should change `HEADERS` to `HEADERS_BASE`

Currently it is
```cmake
install(FILES ${HEADERS}
		DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${libIncludeSubdir}
		COMPONENT Headers)
```
However it should be
```cmake
install(FILES ${HEADERS_BASE}
		DESTINATION ${CMAKE_INSTALL_INCLUDEDIR}/${libIncludeSubdir}
		COMPONENT Headers)
```

**Comment by jkriege2** [comment]
yes, you are right ... fixed with commit https://github.com/jkriege2/JKQtPlotter/commit/a80ea3a24aa39f96d78f834b78a7ad610e7715ed

THANKS!
