### ISSUE TITLE
Please clarify in the comment...

### ISSUE THREAD

**Issue by igormironchik** [jkriege2/JKQtPlotter#74]
Hello.

Please clarify in the comment of the `JKQTMathText` method:

```cpp
/** \brief draw a representation to the <a href="http://doc.qt.io/qt-5/qpainter.html">QPainter</a> object at the specified position */
void draw(QPainter& painter, double x, double y, bool drawBoxes=false);
```
What `x` and `y` should point to. Is it a top-left corner, center, or something else?

I tried to figure out and check in the code, but if to set `x` and `y` to `0`, then there is no image drawn, whereas with:

```cpp
void draw(QPainter& painter, unsigned int flags, QRectF rect, bool drawBoxes=false);
```
with `rect = QRectF( QPointF( 0, 0 ), size )` everything draws correctly.

Thanks.

**Comment by jkriege2** [comment]
I will update the comment soon with a better explanation ... thanks for mentioning!

For now a quick description: Looking at this example output:
![jkqtmathtext_brace_tri](https://user-images.githubusercontent.com/11967523/176945725-aeb3b6d8-e22c-4844-8bf1-60e851adc49a.png)
The position (x,y) will be on the left border where the baseline (blue dashed) intersects with the left bounding rect border (red dashed). So on the left of the text. letter like A will extend above y (i.e. <y) and the descent will be below y (i.e. y>0).

Does this help?

I'll let you  know, hen the doc has been updated (with a proper drawing also!)

**Comment by igormironchik** [comment]
Thank you. Yes, it helped.

**Comment by jkriege2** [comment]
fixed via https://github.com/jkriege2/JKQtPlotter/commit/9a13e5127ab3edf0801e90de02a34140b506625a

**Comment by jkriege2** [comment]
See http://jkriege2.github.io/JKQtPlotter/class_j_k_q_t_math_text.html#ace4fa59fd6101d2396b150ca2d5acf7b
