### ISSUE TITLE
Could you implement `\over` command?

### ISSUE THREAD

**Issue by igormironchik** [jkriege2/JKQtPlotter#75]
Hello. The subject...

Currently command `\over` is not implemented. For example:

```
x = {-b \pm \sqrt{b^2-4ac} \over 2a}
```
draws in one line with unknown character in place of `\over`, whereas it should render as:

$x = {-b \pm \sqrt{b^2-4ac} \over 2a}$

Thanks.

**Comment by jkriege2** [comment]
The way the parser is implemented, it would be quite hard to implement \over ... bute you can use the LaTeX standards \frac, \stackrel, ...
