### ISSUE TITLE
Enable set font size to `JKQTMathText` in pixels.

### ISSUE THREAD

**Issue by igormironchik** [jkriege2/JKQtPlotter#76]
Hello. The subject.

Corresponding to the code:

```cpp
class JKQTMATHTEXT_LIB_EXPORT JKQTMathText : public QObject {
    protected:
        /** \brief base font size in points */
        double fontSize;
```
Font size in `JKQTMathText` is set with points, that is platform dependent, as Qt for a long time is not accurate in this question. I did a lot of applications where were necessary to see the same picture on all devices, and I was forced to calculate fonts' sizes by hands and set them in pixels.

Thanks.

**Comment by jkriege2** [comment]
implemented in https://github.com/jkriege2/JKQtPlotter/commit/2ef181301bf93552b7555c792254152cf7c86da2 ... hope it works for you
