### ISSUE TITLE
`JKQTMathText` with font set in pixels size produces different sizes

### ISSUE THREAD

**Issue by igormironchik** [jkriege2/JKQtPlotter#79]
With the same font, with the same size in pixels, on the same machine, the same math expression but under different OSes `JKQTMathText` produces different sizes of pixmaps.

On linux I see with the same math expression size `(47,7x21,3)` and on Windows `(45x21,3)`.

**Comment by jkriege2** [comment]
Hmmm ... that's not much of a difference ... since the aim of the lib is not really pixel to pixel equality on all systems, I will not fix this ... but I would be happy to merge a PR with a fix!

**Comment by igormironchik** [comment]
Hello.

I'm ready to do such PR, no problem. I did a small research. Look, for example, in the following code:

```cpp
double JKQTMathTextWhitespaceNode::Type2PixelWidth(Types type, JKQTMathTextEnvironment currentEv, QPaintDevice* pd) const
{
    const QFontMetricsF fm(currentEv.getFont(parentMathText), pd);
#if (QT_VERSION>=QT_VERSION_CHECK(5, 15, 0))
    const double em=fm.horizontalAdvance(QChar(0x2003));//currentEv.fontSize;
    const double sp=fm.horizontalAdvance(' ');//currentEv.fontSize;
#else
    const double em=fm.width(QChar(0x2003));//currentEv.fontSize;
    const double sp=fm.width(' ');//currentEv.fontSize;
#endif
    const double en=em/2.0;
    switch (type) {
        case WSTNormal: return sp;
        case WSTNonbreaking: return sp;
        case WST1en: return en;
        case WST1em: return em;
        case WSThair: return em/12.0;
        case WSTthin: return em/6.0;
        case WSTnegthin: return -em/6.0;
        case WSTmedium: return em*2.0/9.0;
        case WSTnegmedium: return -em*2.0/9.0;
        case WSTthick: return em*5.0/18.0;
        case WSTnegthick: return -em*5.0/18.0;
        case WSTthicker: return em/3.0;
    }
    return 0.0;
}
```

You use `QFontMetricsF` and `horizontalAdvance()`. The problem is that this `horizontalAdvance()` produces different values for the same font and size on different platforms. So, on Windows we get, for example, 22.0, and on Linux we get 21.5469. That leads to different sizes of the generated Math expression picture.

I created [QTBUG-104790](https://bugreports.qt.io/browse/QTBUG-104790), that received P3. Until this issue won't be fixed the problem can't be solved. Looking forward for the newer version of Qt.
