### ISSUE TITLE
Bug with multiple inheritance with Q_GDAGET with CLANG

### ISSUE THREAD

**Issue by igormironchik** [jkriege2/JKQtPlotter#80]
[Question on StackOverflow](https://stackoverflow.com/questions/72920443/is-it-possible-to-fix-failed-build-on-macos)

**Comment by igormironchik** [comment]
I reproduced with small example [here](https://github.com/igormironchik/qgadget_macos_check)

**Comment by igormironchik** [comment]
I guess, that this is Qt's bug.

**Comment by igormironchik** [comment]
[Qt's bug](https://bugreports.qt.io/browse/QTBUG-104874)

**Comment by igormironchik** [comment]
This issue affects any platform when building with Clang.

**Comment by igormironchik** [comment]
To reproduce:

```cpp
#pragma once

#include <QObject>


class Gadget1 {
	Q_GADGET
};

class Gadget2 {
	Q_GADGET
};

class Object1
	:	public QObject
{
	Q_OBJECT
};

class Check
	:	public Object1
	,	public Gadget1
	,	public Gadget2
{
	Q_OBJECT
};
```

**Comment by jkriege2** [comment]
Possibly I can remove some Q_GADGET declarations, but can't look into it before next week

**Comment by igormironchik** [comment]
No problem. the work in Qt on this issue is in progress. I believe that Qt 6.3.2 will be with fix. I just wanted to test one my application on MacOS and find out this problem, so the time is not a problem.

**Comment by jkriege2** [comment]
I added an AppVeyor build for MacOS that reproduces said problem:
https://ci.appveyor.com/project/jkriege2/jkqtplotter/build/job/bovmf7qv07t0fxoc

**Comment by jkriege2** [comment]
I think I implemented a workaround solution (for CLANG only) in https://github.com/jkriege2/JKQtPlotter/commit/ece49f2d2b5477e8db901c391b9dcfb47d3b3a6f so the lib works on CLANG without problems. The workaround can be switched off as soon as it is resolved in Qt, starting from the resolving version(s). 

Will close this issue when the Appveyor build succeeds. 

Please reopen or comment if there are further problems tied to this issue!

**Comment by jkriege2** [comment]
Worked around via https://github.com/jkriege2/JKQtPlotter/commit/ece49f2d2b5477e8db901c391b9dcfb47d3b3a6f
