### ISSUE TITLE
Possibility to save the current plot as image with different stylesheet

### ISSUE THREAD

**Issue by sim186** [jkriege2/JKQtPlotter#83]
I don't know if it is possible to do it out of the box, my application has a dark mode, but for printing purposes I would like to save the plot with a different background (through the right click action save plot). It is possible to change those values during the saving or should I implement them on my own?

Thanks for the answer.

**Comment by jkriege2** [comment]
actually that should work, if you set a color in JKQTBasePlotterStyle::exportBackgroundBrush

**Comment by sim186** [comment]
Hi,

I checked the option you mentioned, I think this one is changing color just on the widget background, but noy on the plot background for which I cannot find any option.
For this option setted, I get:
`ui->plot->getPlotter()->setExportBackgroundBrush(QColor("yellow"));`

![image](https://user-images.githubusercontent.com/18590835/183414950-a65f546e-47ae-48d3-b8e9-5b0a3ecb7498.png)

but the plot background itself stays dark gray.

**Comment by jkriege2** [comment]
Hmmm ... then maybe plotBackgroundBrush is also a dark grey ... you could set that to transparent ... but note that then still all lines are dark ... you could maybe load a sytle-file using JKQTBasePlotter::loadCurrentPlotterStyle() before exporting and reset it afterwards ... currently I don't see any other option. a possibility would be to add a second style that is applied during export/printing ... but that's not currently implemented.

**Comment by sim186** [comment]
> 

Yeah, exactly this is what I was thinking. The problem is that I need to catch a signal when the print/export function is triggered. When I connect it on the QAction this action trigger is actually happening after all the export phase. I need to change the style in between right after when the action is clicked.

Do you have idea?

**Comment by jkriege2** [comment]
I would have to think about how to best do that ... let me get back to you in a few days?

**Comment by sim186** [comment]
> I would have to think about how to best do that ... let me get back to you in a few days?

Yes sure. Whenever you want. I already nice that you answer so quick! Thanks for your work again!

**Comment by jkriege2** [comment]
I've been giving this a thought .... a general solution is not easy to implement, as each graph and the plot, axes,legends, may have overwritten settings (e.g. colors). The style only define presets and rules e.g. how to choose colors automatically. So there is no facility to store the complete setup of the plot and restore it later. therefore such a feature would not really work, because after applying the export/print-style and the reapplying the draw-style, all user-overwrites would be lost ...

I will think about whether it's possible to write a storage frame-work for everything. If I will do that, I could implement the requested feature ... maybe until then, I could at least provide you with signals before and after the export/print starts/ends.

Would that help?

**Comment by sim186** [comment]
> I've been giving this a thought .... a general solution is not easy to implement, as each graph and the plot, axes,legends, may have overwritten settings (e.g. colors). The style only define presets and rules e.g. how to choose colors automatically. So there is no facility to store the complete setup of the plot and restore it later. therefore such a feature would not really work, because after applying the export/print-style and the reapplying the draw-style, all user-overwrites would be lost ...
> 
> I will think about whether it's possible to write a storage frame-work for everything. If I will do that, I could implement the requested feature ... maybe until then, I could at least provide you with signals before and after the export/print starts/ends.
> 
> Would that help?

Have the signal slot available for this case would be already really helpful. Thanks!

**Comment by jkriege2** [comment]
Hi!

have a look at this commit: https://github.com/jkriege2/JKQtPlotter/commit/16df80c8c761d29976a5d9fcdb2d55a22bf6df88 ... does it suffice?

Best,
JAN

**Comment by sim186** [comment]
Sorry for the late reply. Yes it did the job perfectly! Thanks!
