### ISSUE TITLE
How to deal with large dataset

### ISSUE THREAD

**Issue by sim186** [jkriege2/JKQtPlotter#84]
Hi,

I'm here again. I noticed that swiching from a scattered plot to a line plot increase a lot the computation time during the "setGraphVisibile" call. Take into account that my datasets have more than 10000 points, I profiled the code and looks like that the most expensive part is exactly the setGraphVisible call. My question is: I'm using it in the right way or is expected to have such a different during the rendering? (I mean in principle I expect that a scatter is easier to draw than a line chart).

Scatter:
<img width="879" alt="image" src="https://user-images.githubusercontent.com/18590835/184091225-0c1f9cef-ab27-456d-99e9-f6652a6f8be9.png">
Line:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/18590835/184091325-4d3253f3-e565-4234-994a-56aacea6f676.png">

**Comment by jkriege2** [comment]
Hi!
I will look into this and more broadly the speed issues, but it will take me some time, as I want to finish something else first.

Best,
JAN

**Comment by jkriege2** [comment]
Hi!

I'm currently looking into this, but don't really understand the problem. Could you answer these questions?
1. What do you mean by "scatter" and "Line"? A JKQTPXYParametrizedScatterGraph and a JKQTPXYLineGraph? Or a JKQTPXYLineGraph with symbols, setDrawLines(false) and vice-versa?
2. The setGraphVisible()-call causes a replot, that's why it deoends on the type of plots.
3. If you don't want an immediate update of the plot, you can call JKQTPlotter::setPlotUpdateEnabled(false), then do all your changes to the plots and then call JKQTPlotter::setPlotUpdateEnabled(true); JKQTPlotter::redrawPlot(); This is most useful, if you cange several plot properties at once. Does this cover your usecase?

Best,
Jan

**Comment by jkriege2** [comment]
Also: which symbol do you use? The more coplex symbols take longer to draw than the simpler ones!

**Comment by jkriege2** [comment]
You can also look at https://github.com/jkriege2/JKQtPlotter/tree/master/examples/speed (which I will improve soon) to test some use-cases!

**Comment by sim186** [comment]
Hi,
 thanks for the reply. To answer to your questions:
> 1. What do you mean by "scatter" and "Line"? A JKQTPXYParametrizedScatterGraph and a JKQTPXYLineGraph? Or a JKQTPXYLineGraph with symbols, setDrawLines(false) and vice-versa?

For line graph I mean the JKQTPXYLineGraph, and for the scatter, as you said I mean JKQTPXYParametrizedScatterGraph. The line graph I totally removed the symbols using the method `setSymbolType(JKQTPNoSymbol);`

> 2. The setGraphVisible()-call causes a replot, that's why it deoends on the type of plots.

I see. Infact after reading this I did another try, which is stopping the continuos update of the plot before the call of the setGraphVisible call, and now is way way faster. I tried also to profile again the code and I lowered the amount by almost 23%! Huge Thanks for the hint!
<img width="656" alt="image" src="https://user-images.githubusercontent.com/18590835/186400019-bb7f05a6-4def-4baa-8b26-14f1e16419ff.png">

> 3. If you don't want an immediate update of the plot, you can call JKQTPlotter::setPlotUpdateEnabled(false), then do all your changes to the plots and then call JKQTPlotter::setPlotUpdateEnabled(true); JKQTPlotter::redrawPlot(); This is most useful, if you cange several plot properties at once. Does this cover your usecase?

As said before, I don't need a real time update of the plot, therefore disable the update of the plot while setting visibility is totally fine and did the job perfectly.

> You can also look at https://github.com/jkriege2/JKQtPlotter/tree/master/examples/speed (which I will improve soon) to test some use-cases!

As suggested into the tutorial (on which I already took a look before) I disabled the antialiasing option but I didn't notice any big difference.
```
plot.getPlotter()->setUseAntiAliasingForGraphs(false);
plot.getPlotter()->setUseAntiAliasingForSystem(false);
plot.getPlotter()->setUseAntiAliasingForText(false);
```

On my side I don't need anything more. So if you like you can also close the issue.

**Comment by jkriege2** [comment]
Great!
I will leave this open for a few more days, as I'm currently implementy speed improvements to the plotting ... especially for line-charts and if you zoom in.

**Comment by jkriege2** [comment]
About the anti-aliasing ... strange ... for me it makes a huge difference ? WHich Qt version do you use?

**Comment by jkriege2** [comment]
https://github.com/jkriege2/JKQtPlotter/commit/03031e3762992ac079b1987c60d7581533beb917 adds a hige speed improvement to JKQTPXYLineGraph ... see http://jkriege2.github.io/JKQtPlotter/class_j_k_q_t_p_graph_lines_compression_mixin.html

**Comment by jkriege2** [comment]
I just improved plotting speed for line-graphs even a bit more ... see updated table in speed example ... maybe that helps you!

**Comment by sim186** [comment]
> About the anti-aliasing ... strange ... for me it makes a huge difference ? WHich Qt version do you use?

I'm using Qt 5.15.

**Comment by sim186** [comment]
> I just improved plotting speed for line-graphs even a bit more ... see updated table in speed example ... maybe that helps you!

Sounds great! I will try out. Thanks.
