### ISSUE TITLE
Gray scale

### ISSUE THREAD

**Issue by nn-no1** [jkriege2/JKQtPlotter#85]
Which function is used for gray scale map
My data is a gray-scale image of “byte *”  （0-255）

**Comment by jkriege2** [comment]
I think you're looking for this:
- http://jkriege2.github.io/JKQtPlotter/class_j_k_q_t_p_math_image.html
- http://jkriege2.github.io/JKQtPlotter/_j_k_q_t_plotter_image_plot_no_datastore.html
:
This class implements the mixin http://jkriege2.github.io/JKQtPlotter/class_j_k_q_t_p_color_palette_style_and_tools_mixin.html which allows to set a palette (and configure range etc.). For grayscale use JKQTPMathImage::setColorPalette(JKQTPMathImageGRAY)

See http://jkriege2.github.io/JKQtPlotter/group__jkqtplotter__imagelots__tools.html#gaae2f1de8b42bb1734243b4201f4aa72d for more palettte options

**Comment by nn-no1** [comment]
I got it！ What a good project！Thank you for your efforts!





---Original---
From: "Jan W. ***@***.***&gt;
Date: Thu, Aug 25, 2022 15:27 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [jkriege2/JKQtPlotter] Gray scale (Issue #85)




 
I think you're looking for this:
  
http://jkriege2.github.io/JKQtPlotter/class_j_k_q_t_p_math_image.html 

http://jkriege2.github.io/JKQtPlotter/_j_k_q_t_plotter_image_plot_no_datastore.html
 :
 This class implements the mixin http://jkriege2.github.io/JKQtPlotter/class_j_k_q_t_p_color_palette_style_and_tools_mixin.html which allows to set a palette (and configure range etc.). For grayscale use JKQTPMathImage::setColorPalette(JKQTPMathImageGRAY) 
 
See http://jkriege2.github.io/JKQtPlotter/group__jkqtplotter__imagelots__tools.html#gaae2f1de8b42bb1734243b4201f4aa72d for more palettte options
