### ISSUE TITLE
Image output scaling

### ISSUE THREAD

**Issue by nmielcarek** [jkriege2/JKQtPlotter#96]
Greetings,

I'm curious why this 1.1 scaling factor exists here in JKQTBasePlotter::saveAsPixelImage:
https://github.com/jkriege2/JKQtPlotter/blob/master/lib/jkqtplotter/jkqtpbaseplotter.cpp#L4002

Whenever I try to save a png image, it always creates an empty transparent region around the plot due to that extra scaling which isn't desired.

OS: Linux (Fedora 36)

Thanks for the great library!
-Nathan

**Comment by jkriege2** [comment]
fixed via https://github.com/jkriege2/JKQtPlotter/commit/d23ea0a79ebeddd1d63e4f1ea138de1192e6a9f6
