### ISSUE TITLE
Plots depth

### ISSUE THREAD

**Issue by sim186** [jkriege2/JKQtPlotter#97]
Since I cannot find any reference in the documentation, is there any way to decide, in case of multiple graph shown in the same plot, which one should appear at top and which one in foreground?

I guess them are shown in the order how we call appGraph. If I want to resort them should I remove and then add again in the order I prefer?

**Comment by jkriege2** [comment]
Hi!
hhmmm ... you're right, there is no API to do that ... but I would see that as an issue that should be solved ... I'll see what I can do ... until then:

**Comment by jkriege2** [comment]
Hmmm ... looking at the code: Management of graphs is really a mess ... I think I will clean that up right now ;-)

**Comment by jkriege2** [comment]
Should be solved by https://github.com/jkriege2/JKQtPlotter/commit/ebd1a29e1dd0ea7cfab1b6d3bb25ff50fe5713b9

**Comment by sim186** [comment]
Sounds perfect! I will try it soon!

**Comment by jkriege2** [comment]
solved via https://github.com/jkriege2/JKQtPlotter/commit/ebd1a29e1dd0ea7cfab1b6d3bb25ff50fe5713b9
